version: '3.8'

services:
  sleek-airflow:
    build: .
    image: sleek-airflow:latest
    volumes:
      - .:/app
      - ./airflow:/opt/airflow
      - ./logs:/opt/airflow/logs  # Persistent logs volume
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/app:/opt/airflow
      - AIRFLOW__CORE__LOGGING_LEVEL=INFO
      - AIRFLOW__CORE__DAG_CONCURRENCY=1  # Limit concurrent tasks
      - AIRFLOW__CORE__PARALLELISM=2
      - AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG=1
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
      - AIRFLOW__CORE__EXECUTE_TASKS_NEW_PYTHON_INTERPRETER=True
    command: airflow standalone
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Add resource constraints
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2.0'
    #       memory: 4G
    #     reservations:
    #       cpus: '0.5'
    #       memory: 1G
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  storedata-db:
    image: influxdb:2
    ports:
      - 8086:8086
    env_file: ".env"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 5s
      timeout: 2s
      retries: 12
    volumes:
      - influxdb-data:/var/lib/influxdb2
    restart: unless-stopped

  data-pusher:
    build: ./data-pusher
    image: data-pusher:latest
    depends_on:
      storedata-db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  influxdb-data: