name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          if [ -f pytest.ini ] || [ -d tests ]; then pip install pytest; pytest; fi

      - name: Build Docker image
        run: |
          docker build -t my-app:latest .

      - name: Run tests inside Docker
        run: |
          docker run --rm my-app:latest pytest || true
        # Remove '|| true' if you want the workflow to fail on test errors

      # Optional: Push Docker image to Docker Hub or GitHub Container Registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push Docker image
        run: |
          docker tag mlops-sales-prediction:latest ${{ secrets.DOCKERHUB_USERNAME }}/mlops-sales-prediction:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlops-sales-prediction:latest